name: GitHub Actions test
on: 
  push:
    branches:
      - frontend
jobs:
  github_actions_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: DOCKER_BUILDKIT=1
      - run: sudo docker-compose -f docker-compose.prod.yml down
      - run: sudo docker-compose -f docker-compose.prod.yml build
      - run: sudo docker-compose -f docker-compose.prod.yml up
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
