name: GitHub Actions test
on: 
  push:
    branches:
      - frontend
jobs:
  github_actions_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - run: ls -a
      - run: docker-compose build
      - run: docker-compose up
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
